config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :goals, only: [:create, :destroy, :edit, :update]
  end
  resource :session, only: [:new, :create, :destroy]
  end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string           not null
#  privacy    :string           not null
#  status     :string           default("Incomplete")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base
  STATUSES = ["Incomplete", "Complete"]
  PRIVACIES = ["Private", "Public"]

  validates :user, :title, :privacy, presence: true
  validates :privacy, inclusion: { in: PRIVACIES }
  validates :status, inclusion: { in: STATUSES }
  belongs_to :user

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  session_token   :string           not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :goals

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password)
    nil
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def private_goals
    goals.select { |goal| goal.privacy == "Private" }
  end

  def public_goals
    goals.reject { |goal| goal.privacy == "Private" }
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def log_in!(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def log_out!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
    
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def goal_params
    params.require(:goal).permit(:title, :privacy)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    else
      log_in!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @goal = Goal.new
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input
    type='hidden'
    name='authenticity_token'
    value='#{form_authenticity_token}'>".html_safe
  end

  def privacy_checked(goal, value)
    if (goal.privacy.nil? && value == "Private") || goal.privacy == value
      "checked"
    else
      nil
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<% action = @goal.persisted? ? edit_user_goal_url(current_user, @goal) : user_goals_url(current_user) %>
<% method = @goal.persisted? ? "PATCH" : "POST" %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token %>

  <label>New Goal
    <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label> <br />

  <label>Privacy <br />
    <input type="radio"
           name="goal[privacy]"
           value="Private"
           <%= privacy_checked(@goal, "Private") %>>Private<br />
    <input type="radio"
           name="goal[privacy]"
           value="Public"
           <%= privacy_checked(@goal, "Public") %>>Public<br />
  </label>

  <input type="submit" value="Submit" />
</form>

app/views/goals/_goal.html.erb
<%= goal.title %>
<%= goal.status %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= link_to(current_user.username, user_url(current_user)) %>
  <%= button_to 'Logout', session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1> New user </h1>
<form action='<%= users_url %>' method='post'>
  <%= auth_token %>

  <label>Username
    <input type="string" name="user[username]">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s Page </h1>

<section>
  <h2>Public Goals</h2>
  <%= render @user.public_goals %>
</section>

<% if @user == current_user %>
  <section>
    <h2>Private Goals</h2>
    <%= render @user.private_goals %>
  </section>
<% end %>

<%= render "goals/form" %>